### ISSUE TITLE
Caching: Implement caching for dependencies to speed up your workflow

### ISSUE THREAD

**Issue by adambonsu** [adambonsu/hello_world_hex_ruby__web_rails#14]
```yaml
- name: Cache dependencies
  uses: actions/cache@v2
  with:
    path: vendor/bundle
    key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
    restore-keys: |
      ${{ runner.os }}-gems-

```
